#!/usr/bin/env bash
# Resumen interactivo de configuración para Render

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     ✅ PROYECTO PREPARADO PARA RENDER - RESUMEN VISUAL        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 ESTADÍSTICAS DEL PROYECTO"
echo "─────────────────────────────────────────────────────────────────"
echo ""

# Contar archivos
REACT_FILES=$(find src -name "*.jsx" 2>/dev/null | wc -l)
PYTHON_FILES=$(find api -name "*.py" 2>/dev/null | wc -l)
CONFIG_FILES=$(find . -maxdepth 1 -name "*.config.js" -o -name "*.yaml" 2>/dev/null | wc -l)

echo "  📱 Componentes React: $REACT_FILES archivos"
echo "  🔌 Backend Python: $PYTHON_FILES archivos"
echo "  ⚙️  Configuración: $CONFIG_FILES archivos"
echo ""

echo "📦 DEPENDENCIAS"
echo "─────────────────────────────────────────────────────────────────"
echo ""

if [ -f "package.json" ]; then
    REACT_DEPS=$(grep -c "\".*\":.*\"" package.json 2>/dev/null || echo "?")
    echo "  📦 Dependencias Node.js instaladas: $REACT_DEPS"
fi

if [ -f "api/requirements.txt" ]; then
    PYTHON_DEPS=$(wc -l < api/requirements.txt)
    echo "  🐍 Dependencias Python: $PYTHON_DEPS paquetes"
fi
echo ""

echo "🚀 ARCHIVOS PARA RENDER"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  ✅ render.yaml              - Configuración de Render"
echo "  ✅ Procfile                 - Fallback para deploy"
echo "  ✅ build.sh                 - Script de construcción"
echo "  ✅ .env.example             - Variables de entorno"
echo ""

echo "📚 DOCUMENTACIÓN CREADA"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  📖 README_DEPLOY.md         - Resumen ejecutivo"
echo "  📖 DEPLOY_RENDER.md         - Guía paso a paso"
echo "  📖 CHECKLIST_DEPLOY.md      - Checklist pre/post deploy"
echo "  📖 ARCHITECTURE.md          - Diagramas y flujos"
echo "  📖 RENDER_SETUP_COMPLETE.md - Cambios realizados"
echo ""

echo "🛠️  SCRIPTS ÚTILES"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  🔍 bash verify-render-config.sh"
echo "     → Verificar configuración antes de desplegar"
echo ""
echo "  ⚙️  bash setup-local.sh"
echo "     → Configurar ambiente local para desarrollo"
echo ""

echo "🎯 CHECKLIST RÁPIDO"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  ANTES DE DESPLEGAR:"
echo "  ☐ git add . && git commit && git push"
echo "  ☐ bash verify-render-config.sh (sin errores)"
echo ""
echo "  EN RENDER DASHBOARD:"
echo "  ☐ New Web Service → GitHub repo"
echo "  ☐ New PostgreSQL Database"
echo "  ☐ Esperar build (2-3 minutos)"
echo "  ☐ Revisar Logs (sin errores)"
echo ""
echo "  POST-DEPLOY:"
echo "  ☐ Acceder a https://portfolio-api.onrender.com"
echo "  ☐ Probar registro/login"
echo "  ☐ Probar API endpoints"
echo ""

echo "📍 URLS IMPORTANTES"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  🌐 Dashboard Render:    https://dashboard.render.com"
echo "  📖 Documentación:       https://render.com/docs"
echo "  🔗 Tu App (post-deploy): https://portfolio-api.onrender.com"
echo ""

echo "💡 INFORMACIÓN IMPORTANTE"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  ✓ Render tiene plan FREE → Suficiente para empezar"
echo "  ✓ Auto-deploy en cada push a main"
echo "  ✓ PostgreSQL gratis incluida"
echo "  ✓ SSL/HTTPS automático"
echo "  ✓ Plan free se duerme tras 15 min sin actividad"
echo ""

echo "⚡ RENDIMIENTO ESPERADO"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  ⏱️  Build time:            ~2-3 minutos (primera vez)"
echo "  ⏱️  Deployment time:       ~30 segundos"
echo "  🚀 Startup time:          ~30 segundos"
echo "  💾 Memoria disponible:     512MB (plan free)"
echo "  🔄 Workers:               4 (gunicorn)"
echo ""

echo "❓ PRÓXIMAS DUDAS FRECUENTES"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  P: ¿Cuánto cuesta?"
echo "  R: Plan Free es gratuito. Plan pago desde $7/mes"
echo ""
echo "  P: ¿Se duerme la app?"
echo "  R: Plan Free se duerme. Solución: Plan pago o uptime monitor"
echo ""
echo "  P: ¿Los datos se pierden?"
echo "  R: NO. La BD PostgreSQL persiste en plan free"
echo ""
echo "  P: ¿Cómo actualizar código?"
echo "  R: git push main → Render redeploya automáticamente"
echo ""
echo "  P: ¿Cómo cambiar dominio?"
echo "  R: Settings > Custom Domain en dashboard de Render"
echo ""

echo "📞 SI ALGO FALLA"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  1. Revisa logs en Dashboard → Logs"
echo "  2. Lee CHECKLIST_DEPLOY.md → Troubleshooting"
echo "  3. Verifica que DATABASE_URL esté en Environment"
echo "  4. Confirma que dist/ se creó correctamente"
echo "  5. Comprueba que requirements.txt es válido"
echo ""

echo "✨ CONCLUSIÓN"
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "  🎉 Tu proyecto está 100% listo para Render"
echo ""
echo "  Puedes desplegar en 5 minutos sin problemas"
echo "  Frontend + Backend + Base de Datos funcionando juntos"
echo ""
echo "  Documentación completa en:"
echo "  • README_DEPLOY.md"
echo "  • DEPLOY_RENDER.md"
echo "  • CHECKLIST_DEPLOY.md"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 ¡A DESPLEGAR!"
echo ""
